title: "Health Impact in Colombia (2024–2025): Key Indicators, Facto"
description: "Comprehensive dataset of key health indicators for Colombia (2020-2025). Includes mental health metrics (depression, anxiety, suicide rates), healthca"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/health-impact-in-colombia-20242025-key-indicators-factors-and-disease-data"
